### ISSUE TITLE
Timezone problem for --start / --end options

### ISSUE THREAD

**Issue by Sangdol** [scalyr/scalyr-tool#13]
Hello, 

Thanks for the awesome tool.

As there's no settings or arguments for a timezone, the tool gives me logs of wrong time.

For example, if I query with `--start='1:00' --end='2:00'`, it gives me the range between 10:00~11:00 - I live in Germany which is in CEST at the moment.

Being able to set a timezone would be nice.

Thanks,
Sang

**Comment by steve-scalyr** [comment]
Thanks for reporting this. There are a couple of workarounds:

1. Specify a full date/time including time zone. We support a variety of
formats; this might be convenient:

  2011-04-07 23:31:41 UTC

This is YYYY-MM-DD HH:MM:SS.

2. Set a default time zone for your team account. To do this, open the
/scalyr/logs
configuration file <https://www.scalyr.com/file?path=%2Fscalyr%2Flogs> and
enter a line like this:

   timezone: "Europe/Berlin",

If this doesn't help, let us know.

Cheers,
Steve

**Comment by Sangdol** [comment]
Thanks for the quick reply! I'm going to try tomorrow as I am on my home at
the moment.

**Comment by Sangdol** [comment]
Setting the timezone works perfectly. Thanks!
