### ISSUE TITLE
documentation for time format

### ISSUE THREAD

**Issue by paradite** [scalyr/scalyr-tool#15]
The README for `--start=xxx` and `--end=xxx` says:
 > Uses the same syntax as the "Start" field in the log view.

And the documentation [here](https://www.scalyr.com/help/time-reference) says:
<img width="327" alt="screen shot 2017-09-13 at 12 13 07 pm" src="https://user-images.githubusercontent.com/1209810/30359388-ef3667a6-987c-11e7-9305-a75278dddc50.png">

I was quite surprised that it doe not allow some of the common ISO formats for absolute time, so I tried to use `--start='2017-09-12T18:00:00+0800' --end='2017-09-12T21:00:00+0800'` and it actually worked. 

I think the docs should be updated to reflect this because it is very helpful in exporting logs to use absolute time (apart from the unix time from January 1, 1970 in the docs).

**Comment by steve-scalyr** [comment]
Thanks for the feedback! We'll update the documentation to mention ISO
format.

Cheers,
Steve

**Comment by paradite** [comment]
looks like it is already added, thanks!
<img width="1080" alt="screen shot 2017-09-25 at 11 05 50 am" src="https://user-images.githubusercontent.com/1209810/30790906-863b870e-a1e1-11e7-8c0e-15fde175d29c.png">

**Comment by steve-scalyr** [comment]
Thanks again for pointing this out to us.
