### ISSUE TITLE
Need http proxy support for cli tool

### ISSUE THREAD

**Issue by heathdbrown** [scalyr/scalyr-tool#36]
Some enterprises still use http/https proxies.

I can see two ways of doing this setting the standard environment variables.

```
export https_proxy="https://proxy.example.com"
scalyr query
```

Passing proxy as a parameter.

```
scalyr --proxy "https://proxy.example.com" query
```

**Comment by ajtcode** [comment]
@heathdbrown, thank you for submitting pull request (#37). We will review it and follow up shortly.

**Comment by heathdbrown** [comment]
Discussion in the PR need to update a few items to support standard way of grabbing proxies and multiple schemes.
